### ISSUE TITLE
Keyboard layout incorrect on first boot (was: "passphrase for rpool incorrect")

### ISSUE THREAD

**Issue by thethinker990** [saveriomiroddi/zfs-installer#110]
I did your installation and entered my passphrase (2-times), after the installation while I am booting I am entering my passphrase and get this message:
```
Enter passphrase for 'rpool':
Key load error: Incorrect key provided for 'rpool'.
```
I created in KeePass a random word sequence with 43 ch. (171 bits)

Is there a maximum character length?

**Comment by thethinker990** [comment]
Problem was the keyboard layout.

I swaped from EN (QUERTY) to DE (QWERTZ) at the start of the installation process but your script didn't regocnized it.

Maybe you can add a functionality or give a disclaimer.

**Comment by saveriomiroddi** [comment]
Hello!

Glad this was solved.

The script itself is on a different abstraction than the interface configuration; it's (appropriately) unaware, so it's not its domain to consider those factors (there are virtually infinite issues that the user can cause). Of course, if a large amount of users would experience this issue, it would become a UX problem to consider, but as of now, it's isn't the case.

Enjoy ZFS :slightly_smiling_face: .

**Comment by koenvervloesem** [comment]
I just experienced this too. Just like @thethinker990 I ran the graphical installer up to the point of changing the keyboard layout and setting up Wi-Fi, after which I closed and started zfs-installer, so I could reliably enter my six-word Diceware passphrase. I expected it to use the keyboard layout I had just configured, but it wasn't. Would it be difficult to change this behaviour?

**Comment by saveriomiroddi** [comment]
Hello!

> Would it be difficult to change this behaviour?

So! The problem is not beyond difficulty in itself - it's that terminal input (applications) does't have any concept of keyboard layout; it passively uses what it is sent from the desktop environment.  
Alternatively, I can't exclude a bug in the script that, say, removes or corrupts some characters entered.

Can you provide me:

- a sample password that you think may break
- the O/S distro you've attempted to install
- your keyboard layout
- the keyboard layout setting you've changed to

As first step, I'll try to reproduce it.

**Comment by koenvervloesem** [comment]
Thanks for looking into this!

- Sample password: VroomPeulZangerInsectPlegerBoiler9 -> problem: z and a are interpreted as w and q, and 9 as ( or ) (I don't remember)
- Distro: Ubuntu Desktop 20.04.1 LTS
- Keyboard layout: Belgian
- Keyboard layout setting: Belgian (just regular Belgian, no variant chosen)

**Comment by pschnitzer** [comment]
As a quick-fix: You could probably don't hide the password entered, sou you see it in blank characters and you maybe get the issue faster. Just a thought

**Comment by koenvervloesem** [comment]
@saveriomiroddi I have found something that should lead to the solution. If I boot into the system, enter the passphrase (swapping a and a, w and q and so on), and then regenerate the initramfs with `sudo update-initramfs -u` and then reboot, the passphrase is accepted with the right keyboard layout.

It looks to me that the keymap isn't loaded in the original initramfs, and after installing the ZFS packages in your installer script, you should regenerate the initramfs so it loads the keymap because the `zfs-initramfs` package has installed an initramfs hook to add the keymap. For some reason that hasn't happened.

**Comment by saveriomiroddi** [comment]
Hello everybody!

This Stack Overflow question/answer mimics @koenvervloesem's findings. I'll update the script today or tomorrow, and release it, which should fix the problem.

Providing a way to display the password is an interesting UX idea, although it wouldn't solve this specific problem. I'll an issue though, because it's a good UX practice (I hate when I want to see what I'm typing, and I'm prevented by design...).

Thanks for the research and the patience™ :grin:

**Comment by saveriomiroddi** [comment]
Hello everybody!

I've just released the new installer stable version, which includes this fix.

Many thanks @koenvervloesem for the help - it would have been quite difficult for me to figure out the solution.

If this happened again (:exploding_head:), feel free to reopen the issue.
