### ISSUE TITLE
Adding Support for Kubuntu 20.04

### ISSUE THREAD

**Issue by Hornochs** [saveriomiroddi/zfs-installer#192]
Since I work in IT I should have know better about tickets 🤣

Like I said in my first issue, Script runs fine until it tells me, the installer should start. But it won't. Then I have no option to install it on the zfs Pool.

**Comment by Hornochs** [comment]
@saveriomiroddi made an answer while I was typing this ticket 😅

https://github.com/saveriomiroddi/zfs-installer/issues/191#issuecomment-828454359

**Comment by saveriomiroddi** [comment]
At a quick glance, KUbuntu doesn't ship with ZFS packages installed. Typically (immensely annoying) Linux fragmentation issue. Should be fairly easy to fix.

Generally speaking, if one posts the logs in issues, I'll be able to work on the issue quicker. No need to do this anymore, since I've found where the problem is.

**Comment by saveriomiroddi** [comment]
Support release in the stable channel.
