### ISSUE TITLE
Error while accessing newly created temp OS volume 

### ISSUE THREAD

**Issue by andrey42** [saveriomiroddi/zfs-installer#8]
Hi.
Encountered the following error in the script while opening temp OS pool
```
Creating new GPT entries.
The operation has completed successfully.
The operation has completed successfully.
The operation has completed successfully.
mkfs.fat 4.1 (2017-01-24)
Setting up swapspace version 1, size = 2 GiB (2147479552 bytes)
no label, UUID=a87000ed-0e27-4945-b8ae-37157e88e89f
Problem opening /dev/zvol/rpool/os-install-temp for reading! Error is 2.
The specified file does not exist!
``` 
Last lines from install log:

```
+ create_temp_volume
+ zfs create -V 10G rpool/os-install-temp
++ readlink -f /dev/zvol/rpool/os-install-temp
+ v_temp_volume_device=/dev/zvol/rpool/os-install-temp
+ sgdisk -n1:0:0 -t1:8300 /dev/zvol/rpool/os-install-temp
```

**Comment by saveriomiroddi** [comment]
Hello! Thanks for opening the issue :smile: I'll check the problem out over the next few days, then get back to you.

**Comment by andrey42** [comment]
I believe the error might be caused by either delayed or errored volume spawn.
```zfs create -V 10G rpool/os-install-temp```
 volume command is expected to execute synchronously,  so, might be useful to check at least return code and status, for example with history command:
```zpool history $v_rpool_name```

**Comment by saveriomiroddi** [comment]
> I believe the error might be caused by either delayed or errored volume spawn.
> `zfs create -V 10G rpool/os-install-temp`
> volume command is expected to execute synchronously, so, might be useful to check at least return code and status, for example with history command:
> `zpool history $v_rpool_name`

I need to give a detailed look, however, at a very brief look, I think that the case of `zfs create` exiting with error can be excluded, because the script runs with `set -o errexit`, which would cause abortion before `sgdisk` execution. The case of timing problem however, seems likely!

**Comment by andrey42** [comment]
Ok, then the pool operation is definitely asyncronous, and we have to wait in a loop with, say, 10 seconds, for pool readiness, using 
```zpool list $v_rpool_name -o health -H```
and proceed only after the pool is created and reported as being online.
I"ll make a new patch for this.

**Comment by saveriomiroddi** [comment]
Hello! First of all, a tip  - when you edit a comment in GitHub, the previous revision is _not_ deleted, and can still be accessed. In order to entirely delete previous revisions, click on `edited`, then click on the revision, then `Delete`. Since it seems you wanted to remove the log (supposedly because of private informations), I've deleted the previous revisions for you.

**Comment by saveriomiroddi** [comment]
I've spent a bit of time trying to reproduce the problem. Some thoughts:

1. on my test system (Ubuntu 18.04 Desktop), `zfs create` generates `/dev/zvol/rpool/os-install-temp`, which is not happening in your case (if it was a symlink, `readlink -f` would return the destination). if you wait a little after that, does it turn into a symlink? this could be a good event to wait on, if that'd be the case
2. interestingly, the `health` property does not exist on my test system (!); this confuses me a bit, but also, makes waiting on this property not a working approach; which system are you testing on?
3. could you try to use `udevadm settle`, rather than a `for/sleep` cycle? I prefer to listen to a specific event where possible (in fact, this strategy is used in the `prepare_disks` stage).

**Comment by andrey42** [comment]
My test system is Ubuntu 18.04.3, made live system from official  ISO image. Yep, you are right, after couple seconds the link appears.
As ter earlier trials, the error has not appeared when HDD was completely clean (no prior MBR or GPT). Tried with ```udevadm settle``` placed after zfs create, works now, thanks for the idea. 
Can you try ```sudo zpool list rpool``` does it yields any properties at all ? Normally with Solaris checking status is preferable, because they might be pending maintenance state after creation.

**Comment by saveriomiroddi** [comment]
The issue has been autoclosed by the fix PR (I've merged in master, and released the `stable` branch), but I'll follow up the discussion of course :smile: I'll spin the test machine and submit the command result tomorrow!

**Comment by saveriomiroddi** [comment]
> My test system is Ubuntu 18.04.3, made live system from official ISO image. Yep, you are right, after couple seconds the link appears.
> As ter earlier trials, the error has not appeared when HDD was completely clean (no prior MBR or GPT). Tried with `udevadm settle` placed after zfs create, works now, thanks for the idea.
> Can you try `sudo zpool list rpool` does it yields any properties at all ? Normally with Solaris checking status is preferable, because they might be pending maintenance state after creation.

My bad! I was mistakenly searching the health property on the volume instead of the pool; querying the pool yields the expected value:

```sh
# zpool list rpool -o health -H
ONLINE
```

Now that the fix has been [released](https://github.com/saveriomiroddi/zfs-installer/blob/stable/install-zfs.sh#L455), performing an installation will now wait. Let me know if you have further questions!
